site_name: DaSPi

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: amber
      accent: deep orange

  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs
  
repo_name: j4ggr/DaSPi
repo_url: https://github.com/j4ggr/DaSPi

plugins: 
  search: null
  mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          docstring_section_style: list
          heading_level: 3
          merge_init_into_class: false
          show_bases: true
          show_source: false
          show_root_heading: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_docstring_functions: true
          inherited_members: true
          members_order: alphabetical
          group_by_category: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: 
    - DaSPi: index.md
    - Installing: installing.md
    - Changelog: CHANGELOG.md
  - API:
    - Anova:
      - ANOVA: anova/index.md
      - anova/linear-model.md
    - Plotlib: 
      - Plotting Library: plotlib/index.md
      - Chart:
        - Chart Module: plotlib/chart/index.md
        - plotlib/chart/chart.md
        - plotlib/chart/single-chart.md
        - plotlib/chart/multiple-variate-chart.md
        - plotlib/chart/joint-chart.md
      - Plotter:
        - Plotter Module: plotlib/plotter/index.md
        - plotlib/plotter/plotter.md
        - plotlib/plotter/scatter.md
        - plotlib/plotter/line.md
        - plotlib/plotter/linear-regression.md
        - plotlib/plotter/probability.md
        - plotlib/plotter/parallel-coordinate.md
        - plotlib/plotter/bland-altman.md
        - plotlib/plotter/transform-plotter.md
        - plotlib/plotter/center-location.md
        - plotlib/plotter/bar.md
        - plotlib/plotter/pareto.md
        - plotlib/plotter/jitter.md
        - plotlib/plotter/gaussian-kde.md
        - plotlib/plotter/violine.md
        - plotlib/plotter/errorbar.md
        - plotlib/plotter/standard-error-mean.md
        - plotlib/plotter/spread-width.md
        - plotlib/plotter/confidence-interval.md
        - plotlib/plotter/mean-test.md
        - plotlib/plotter/variation-test.md
      - Facets:
        - Facets Module: plotlib/facets/index.md
        - plotlib/facets/axes-facets.md
        - plotlib/facets/label-facets.md
        - plotlib/facets/stripes-facets.md
    - Statistics:
      - Statistics Library: statistics/index.md
      - Hypothesis:
        - statistics/hypothesis/index.md
      - Estimation:
        - statistics/estimation/index.md
        - statistics/estimation/estimator.md
        - statistics/estimation/process-estimator.md
      - Confidence:
        - statistics/confidence/index.md
  - Examples: examples.md