[project]
  name = "DaSPi"
  version = "2.0.1"
  description = "Visualize and analyze your data with DaSPi. This package is designed for users who want to find relevant influencing factors in processes and validate improvements."
  authors = [
    {name = "Reto Jäggli", email = "reto@jaeggli.email"},]
  dependencies = [
    "matplotlib>=3.11.0",
    "pandas>=3.0.3",
    "statsmodels>=0.14.6",
    "scipy>=1.18.0",
    "numpy>=2.5.0"]
  requires-python = ">=3.13"
  readme = "README.md"
  license = {text = "MIT"}
  [project.urls]
    Repository = "https://github.com/j4ggr/DaSPi"
    Documentation = "https://j4ggr.github.io/DaSPi/"
    Changelog = "https://j4ggr.github.io/DaSPi/CHANGELOG"

[build-system]
  requires = ["pdm-backend"]
  build-backend = "pdm.backend"

[tool.pdm]
  distribution = true

[dependency-groups]
test = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",]
doc = [
    "mkdocs>=1.6.1",
    "mkdocstrings[python]>=1.0.4",
    "mkdocs-material>=9.7.6",]
notebooks = [
    "marimo>=0.23.10",
]

